// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBZjjrG5ndBWwG0PTrHtirE_pFY4IzlUV0',
    appId: '1:675354525036:ios:798b1a71a0c94e33b74749',
    messagingSenderId: '675354525036',
    projectId: 'projet1-c2fba',
    databaseURL: 'https://projet1-c2fba-default-rtdb.firebaseio.com',
    storageBucket: 'projet1-c2fba.appspot.com',
    iosBundleId: 'com.example.mTicket',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCCOrktRjWHm1bo_HpaOqGwfEonzgUJYog',
    appId: '1:675354525036:web:d6c89f1476ed342ab74749',
    messagingSenderId: '675354525036',
    projectId: 'projet1-c2fba',
    authDomain: 'projet1-c2fba.firebaseapp.com',
    databaseURL: 'https://projet1-c2fba-default-rtdb.firebaseio.com',
    storageBucket: 'projet1-c2fba.appspot.com',
    measurementId: 'G-2YMN15WR8L',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCCOrktRjWHm1bo_HpaOqGwfEonzgUJYog',
    appId: '1:675354525036:web:9ca004b6de1d05e0b74749',
    messagingSenderId: '675354525036',
    projectId: 'projet1-c2fba',
    authDomain: 'projet1-c2fba.firebaseapp.com',
    databaseURL: 'https://projet1-c2fba-default-rtdb.firebaseio.com',
    storageBucket: 'projet1-c2fba.appspot.com',
    measurementId: 'G-HMC69LNLYS',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBZjjrG5ndBWwG0PTrHtirE_pFY4IzlUV0',
    appId: '1:675354525036:ios:798b1a71a0c94e33b74749',
    messagingSenderId: '675354525036',
    projectId: 'projet1-c2fba',
    databaseURL: 'https://projet1-c2fba-default-rtdb.firebaseio.com',
    storageBucket: 'projet1-c2fba.appspot.com',
    iosBundleId: 'com.example.mTicket',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyANFckqZV8lHzXtOewvdjX1mpNZH2llOgM',
    appId: '1:675354525036:android:dc4aedf4edd87a0fb74749',
    messagingSenderId: '675354525036',
    projectId: 'projet1-c2fba',
    databaseURL: 'https://projet1-c2fba-default-rtdb.firebaseio.com',
    storageBucket: 'projet1-c2fba.appspot.com',
  );

}